service: sls-middy

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  apiKeys:
    - sfs3embedded-${opt:stage, self:provider.stage}
  usagePlan:
    throttle:
      burstLimit: 10
      rateLimit: 5


functions:
  signup:
    handler: functions/handler.signup
    events:
      - http: POST signup
  info:
    handler: functions/handler.info
    events:
      - http: GET info



